// ajax and loading actions
export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

// Auth actions
export const AUTH_INITIALIZATION_DONE = 'AUTH_INITIALIZATION_DONE';
export const AUTH_LOGGED_IN_SUCCESS = 'AUTH_LOGGED_IN_SUCCESS';
export const AUTH_LOGGED_OUT_SUCCESS = 'AUTH_LOGGED_OUT_SUCCESS';

// User actions
export const USER_CREATED_SUCCESS = 'USER_CREATED_SUCCESS';
export const USER_LOADED_SUCCESS = 'USER_LOADED_SUCCESS';
export const USER_IS_ADMIN_SUCCESS = 'USER_IS_ADMIN_SUCCESS';

// ChatX actions
export const CHATX_MSG_SENT_SUCCESS = 'CHATX_MSG_SENT_SUCCESS';
export const CHATX_INITIAL_MSG_LIST_LOADED_SUCCESS = 'CHATX_INITIAL_MSG_LIST_LOADED_SUCCESS';
export const CHATX_FIRST_MSG_KEY_FETCHED = 'CHATX_FIRST_MSG_KEY_FETCHED';
export const CHATX_NEW_MSG_LIST_LOADED_SUCCESS = 'CHATX_NEW_MSG_LIST_LOADED_SUCCESS';
export const CHATX_CLEAR_SUCCESS = 'CHATX_CLEAR_SUCCESS';


